In [1]:
import numpy as np


In [3]:
x= np.array([40,67,57,90])
print(x)
print(type(x))
print(x.dtype)

[40 67 57 90]
<class 'numpy.ndarray'>
int32


In [5]:
#reshaping an array
a=np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [7]:
#array with range function
c= np.arange(3,20)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [11]:
d = np.array([9.8,7.6,5.4])
np.round(d)

array([10.,  8.,  5.])

In [13]:
np.around((d),3)

array([9.8, 7.6, 5.4])

In [15]:
print(np.around(np.sqrt(d),2))

[3.13 2.76 2.32]


In [25]:
a1 = np.array([[3,4,5,6],[7,2,8,6]])
print(a1)
a1.dtype

[[3 4 5 6]
 [7 2 8 6]]


dtype('int32')

In [27]:
a1_copy1 = a1.astype(str)
print(a1_copy1)

[['3' '4' '5' '6']
 ['7' '2' '8' '6']]


In [31]:
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
print(a2)

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]


In [33]:
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [37]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,5],[7,9]])
print(A.T)
print(A.T)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [81]:
array = np.array([[3, 4, 5],[7,2,8],[9,1,6],[10,9,18]])

In [85]:
#slicing the array
array[1:3,0:2]

array([[7, 2],
       [9, 1]])